### ISSUE TITLE
Great App and can be used for many area

### ISSUE THREAD

**Issue by airobotusa** [MicrosoftDocs/Hololens#14]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb17525-36a9-d993-b774-24fdd800fa0e
* Version Independent ID: c3ec4304-6217-5341-47cf-774070496c73
* Content: [Getting around HoloLens 2](https://docs.microsoft.com/en-us/hololens/hololens2-basic-usage)
* Content Source: [hololens/hololens2-basic-usage.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens2-basic-usage.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by evmill** [comment]
Thank you so much for your compliment!  
Closing this docs issue since nothing needs to be resolved.
