### ISSUE TITLE
Should add AppInstaller

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/Hololens#21]
AppInstaller should be added since it's an app that will likely need to be blocked in some deployments  Microsoft.DesktopAppInstaller_8wekyb3d8bbwe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eb32b97-9c82-352d-deaf-5278a48c05a1
* Version Independent ID: 2e3b5eb7-be36-8b5b-bf97-67b82337cd24
* Content: [Windows Defender Application Control - WDAC](https://docs.microsoft.com/en-us/hololens/windows-defender-application-control-wdac#package-family-names-for-apps-on-hololens)
* Content Source: [hololens/windows-defender-application-control-wdac.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/windows-defender-application-control-wdac.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @evmill
* Microsoft Alias: **v-evmill**

**Comment by evmill** [comment]
Closing this Issue due to live documentation.
https://docs.microsoft.com/en-us/hololens/windows-defender-application-control-wdac#package-family-names-for-apps-on-hololens
