### ISSUE TITLE
Missing documentation for VPN connection on how to add a certificate to the device

### ISSUE THREAD

**Issue by benjamincoven** [MicrosoftDocs/Hololens#24]
### VPN Section

It is indicated that "If certificate is used for authentication for built-in VPN client, the required client certificate needs to be added to user certificate store." However there is no documentation about how to add a certificate to a HoloLens. Is it with the Device Portal? In the apps section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dce8080-d23d-403d-f3a4-3f1aa9708178
* Version Independent ID: f2bd35de-eab6-d0ec-0bf9-7bf4fdcb3172
* Content: [Connect HoloLens to a network](https://docs.microsoft.com/en-us/hololens/hololens-network)
* Content Source: [hololens/hololens-network.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-network.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by evmill** [comment]
Hello @benjamincoven We've got a set of new VPN guides I believe you'll find helpful. 
https://docs.microsoft.com/en-us/hololens/hololens-network#vpn
Also if you need to add a certificate, the easiest way which is part of our feature release this week is certificate manager: https://docs.microsoft.com/en-us/hololens/certificate-manager
