### ISSUE TITLE
MSIX support as well as APPX?

### ISSUE THREAD

**Issue by Wes777** [MicrosoftDocs/Hololens#25]
The guidance asks to look for an APPX file here.  Is MSIX also now supported for sideloading UWP apps on HoloLens 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa5bcb46-0ea7-d1a8-3c77-ef809c8be0ff
* Version Independent ID: d9e3557b-084f-5a32-a8df-d8e97df43d49
* Content: [Manage custom apps for HoloLens](https://docs.microsoft.com/en-us/hololens/holographic-custom-apps)
* Content Source: [hololens/holographic-custom-apps.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/holographic-custom-apps.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by evmill** [comment]
Asked someone and the answer is yes, as long as you still build in the same architecture needed for HoloLens 2 and deploy the needed certificate.
