### ISSUE TITLE
Can Holographic Remoting and Spatial Anchor work together?

### ISSUE THREAD

**Issue by vincentgohzy** [MicrosoftDocs/Hololens#26]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe8e9aed-e15c-dcdb-3f34-4294a453d359
* Version Independent ID: 462381e6-73dd-0745-c268-547afdb16fef
* Content: [Frequently asked questions about HoloLens devices and holograms](https://docs.microsoft.com/en-us/hololens/hololens-faq)
* Content Source: [hololens/hololens-FAQ.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-FAQ.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by evmill** [comment]
Closing due to stale thread.

**Comment by beelia** [comment]
#pleaseclose - not a HoloLens issue
