### ISSUE TITLE
Windows Configuration Designer

### ISSUE THREAD

**Issue by astaikos316** [MicrosoftDocs/Hololens#27]
Trying to figure out how to get the HoloLens 2 CSPs to show in Windows Configuration Designer.  I have it installed from the Windows Store however when looking for the new Policy CSPs for HoloLens 2 that are a part of 20H2, they do not show up in the list of available customizations in advanced configuration mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91011c3c-a047-926b-058b-dad6c68de528
* Version Independent ID: a1254343-5378-fdab-ba8f-202358a28ff4
* Content: [HoloLens 2 release notes](https://docs.microsoft.com/en-us/hololens/hololens-release-notes#windows-holographic-version-20h2)
* Content Source: [hololens/hololens-release-notes.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-release-notes.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by evmill** [comment]
Hello, which policy are you looking to configure? If you are looking for the new Mixed Reality policies you can find them under Runtime settings > Policies > MixedReality. Also please ensure your Windows Configuration Designer is up to date.

**Comment by astaikos316** [comment]
I am using the Designer from the Windows Store.  When I checked for updates it said it was up to date.  Looking under the Policy Settings I do not see a Mixed Reality Section.

**Comment by evmill** [comment]
Can you confirm that you are selecting to provision HoloLens 2 devices? Trying to provision Windows 10 desktop results in not showing these policies. 
If you're still not seeing the policies you're looking for would you submit feedback through Feedback Hub with a repo video and then use the **Share** button so I can forward the bug to the correct team to investigate? Thanks!

**Comment by astaikos316** [comment]
https://aka.ms/AAapdb8  As requested.  Here is the feedback I just left on the Feedback hub.

**Comment by evmill** [comment]
Closing this loop, this bug was fixed in February and WCD was updated via the Store to contain the policies.
