### ISSUE TITLE
Automatic translation errors in the Japanese version

### ISSUE THREAD

**Issue by zxubian** [MicrosoftDocs/Hololens#29]
[Enter feedback here]
 
The[ Japanese version](https://docs.microsoft.com/ja-jp/hololens/hololens2-maintenance) of this page has multiple errors that make the document difficult to comprehend: some language is unnatural (e.g. translating No as いいえ、そうではありません。), and multiple words are just not translated ( see screenshot)

![2021-01-05 10_52_45-HoloLens 2 クリーニング_ よく寄せられる質問 _ Microsoft Docs](https://user-images.githubusercontent.com/8446683/103597687-3033be80-4f44-11eb-9d94-338235cea705.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9b9efc6-78cd-1f1e-bcd5-3e02130b7bd9
* Version Independent ID: 9ce2e642-96f3-ec9c-e8bd-1e5c8846d1e1
* Content: [HoloLens 2 cleaning FAQ](https://docs.microsoft.com/en-us/hololens/hololens2-maintenance)
* Content Source: [hololens/hololens2-maintenance.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens2-maintenance.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by Teresa-Motiv** [comment]
I'm no longer working on the HoloLens docs, but I've filed a bug for this issue so that it can get triaged to the correct group.

**Comment by joyjaz** [comment]
Created ADO Task 34251120: [HoloLens Docs] Incorrect Japanese localization in HoloLens Cleaning page to address the issue.
