### ISSUE TITLE
ARC not available as an offline installer

### ISSUE THREAD

**Issue by HectorAtLMCO** [MicrosoftDocs/Hololens#31]
Hello. While this is an issue pertaining to the Advanced Recovery Companion, I am listing it as an issue with the Holo2 since there is no other documented way of resetting the device to a factory image. My Organization blocks the Windows Store for Security reasons. There is NOTHING that can be done about this. I tried. However, there seems to be no other way to reset the Holo2! My device is bricked and I cannot move forward with my tasks! There needs to be a stand-alone offline installer for the ARC!

**Comment by evmill** [comment]
Hello, I have filled a bug with the ARC team on behalf of this feedback. I understand that certain endpoints need to be reached to create the installer. I have heard feedback like this before and hopefully the addition of yours helps add weight to this need.

I hope that you were able to self service in some way using: [https://docs.microsoft.com/en-us/hololens/hololens-recovery#download-arc-without-using-the-app-store](https://docs.microsoft.com/en-us/hololens/hololens-recovery#download-arc-without-using-the-app-store)
