### ISSUE TITLE
ARC tool on Intune Managed Device

### ISSUE THREAD

**Issue by Kerseymancory** [MicrosoftDocs/Hololens#34]
When the hololens device is managed by Intune and set to block usb connects, reset using arc will fail. The reset would need to either need to be initiated via the MEM portal or from the UI in the device. Have not tested setting the device in safe mode, but I'd image it would fail due to the connection as well.

**Comment by evmill** [comment]
Hello,

Try using [Manual flashing mode](https://docs.microsoft.com/en-us/hololens/hololens-recovery#manual-procedure), this will allow you to flash the device even if it is locked or USB connection is disabled.
