### ISSUE TITLE
Create Hololens 3 Advanced smart with sales to all stores of all cities of all states of all countries of the whole world always please

### ISSUE THREAD

**Issue by AngelZeur** [MicrosoftDocs/Hololens#36]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e67982e-6e73-e5cd-04eb-3c80568a99be
* Version Independent ID: 75498529-c75a-cdb8-43aa-7a87aa523aa3
* Content: [Give us feedback](https://docs.microsoft.com/en-us/hololens/hololens-feedback)
* Content Source: [hololens/hololens-feedback.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-feedback.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by evmill** [comment]
Hello there, 

While I am glad you are enthusiastic, using Docs isn't going to be the best way to reach marketing. I suggest you try own of the two links:
[Microsoft Store - Office Support](https://support.microsoft.com/office/microsoft-store-109d8aed-d32f-4d6f-9c54-ff80871e8637)
[Store & Purchase Inquiry Support](https://support.microsoft.com/account-billing/contact-microsoft-store-support-4f615f2a-6bbd-fd69-6695-ae213d63eef0)
