### ISSUE TITLE
Need Clarification on Code Integrity Protection

### ISSUE THREAD

**Issue by ARGs-code** [MicrosoftDocs/Hololens#37]
The section on Code Integrity doesn't specifically mention the HoloLens 2. Is code integrity protection enabled on the HoloLens 2? Is it configurable via a compliance policy in InTune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbc3f4cf-2024-5b09-cde2-db1e0e876286
* Version Independent ID: ecbe4837-4f6c-e19d-238d-a426f8d8b86f
* Content: [Hardware backed integrity and runtime attestation](https://docs.microsoft.com/en-us/hololens/security-hardware-backed-integrity)
* Content Source: [hololens/security-hardware-backed-integrity.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/security-hardware-backed-integrity.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @evmill
* Microsoft Alias: **v-evmill**

**Comment by evmill** [comment]
Hello @ARGs-code / Andrew. 
There is no way to turn off Code Integrity. Similar to the way HoloLens handles Bitlocker, it is an "always on" style of design. It it not configurable via any means.
