### ISSUE TITLE
Broken link to "Spatial Mapping Design" docs

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/Hololens#4]
Broken link to "Spatial Mapping Design":
https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping-design

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b3eba3-dd78-9322-f17a-2c83ac26fb01
* Version Independent ID: b4eaae08-3fe6-07ff-6dfc-b581abf3c8ed
* Content: [Map physical spaces with HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-spaces)
* Content Source: [hololens/hololens-spaces.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-spaces.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by evmill** [comment]
@hferrone Do you know if the link mentioned above was moved/split/rename/whatever and what we should update this link to be to go to the correct location?

**Comment by hferrone** [comment]
@evmill Is this the article you're looking for? https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping

**Comment by hferrone** [comment]
@evmill Is this the article you're looking for? https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping

**Comment by evmill** [comment]
Link is updated.

**Comment by evmill** [comment]
Resolving issue.
