### ISSUE TITLE
Disable calibration process

### ISSUE THREAD

**Issue by MoritzKoehlerDesign** [MicrosoftDocs/Hololens#48]
I cant find this solution after the new windows update, is there a new way to disable automatic calibration process?
//
Disable calibration

You can also disable the calibration prompt by following these steps:

    Select Settings > System > Calibration.
    Turn off When a new person uses this HoloLens, automatically ask to run eye calibration.
//

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa319ad-e258-52c8-fa7b-aafcfbbdf385
* Version Independent ID: 1484d0bc-8612-f49d-4faa-f574dec49929
* Content: [Improve visual quality and comfort](https://docs.microsoft.com/en-us/hololens/hololens-calibration)
* Content Source: [hololens/hololens-calibration.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-calibration.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **xerxesb**

**Comment by joyjaz** [comment]
This feature has been removed. Docs have been updated. https://review.docs.microsoft.com/en-us/hololens/hololens-calibration?branch=pr-en-us-777
