### ISSUE TITLE
Instructions for Rolling back to previous Version of HoloLens 2 OS provides link for Most Recent Version of HoloLens 2 OS release.

### ISSUE THREAD

**Issue by ARGs-code** [MicrosoftDocs/Hololens#49]
The instructions on this page to roll back a previous version of OS for Hololens 2 directs us to Download the most Recent Hololens 2 release.

This is not useful if we want to roll back to a previous OS version.

Where are the previous OS versions for HoloLens 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a78d719-bf9a-13e4-81ee-4133eb38c4f8
* Version Independent ID: a2955339-7086-7b42-f588-31ee7a53cf3c
* Content: [Manage HoloLens updates](https://docs.microsoft.com/en-us/hololens/hololens-updates)
* Content Source: [hololens/hololens-updates.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-updates.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by Teresa-Motiv** [comment]
@joyjaz, can you take a look at this? Thx.

**Comment by joyjaz** [comment]
We only provide the most recent release for download via this link. If a customer wishes to download to an earlier version, they must contact CSS for the file.

**Comment by ARGs-code** [comment]
@joyjaz I don't believe this issue should have been closed. The documentation states the following

"To revert to a previous version of HoloLens 2, follow these steps:

    Make sure that you don't have any phones or Windows devices plugged in to your computer.
    On your computer, download the Advanced Recovery Companion from the Microsoft Store.
    Download the most recent HoloLens 2 release..."
    
These are **not** instructions on how to revert to a previous version of HoloLens 2 OS. Your solution for this is unhelpful.
