### ISSUE TITLE
Should "because" be "before"

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/Hololens#51]
In the statement "new updates because they can pause again",  should "because" be "before"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a78d719-bf9a-13e4-81ee-4133eb38c4f8
* Version Independent ID: a2955339-7086-7b42-f588-31ee7a53cf3c
* Content: [Manage HoloLens updates](https://review.docs.microsoft.com/en-us/hololens/hololens-updates)
* Content Source: [hololens/hololens-updates.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-updates.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by joyjaz** [comment]
Fixed. Thanks!
