### ISSUE TITLE
Access Hololens2 Camera Buffer while being used by Dynamics 365 Remote Assist

### ISSUE THREAD

**Issue by jnanadarshan** [MicrosoftDocs/Hololens#54]
We have a bunch of Hololens 2 that we are using for Field Service Engineers using Microsoft Dynamics 365 Remote Assist on Hololens 2. Now we want to apply some Computer Vision algorithms in real-time so that our remote experts can see both Remote Assist calls and a second stream with some CV algorithms applied. Is it possible to access Hololens 2 Camera while it is being used by Remote Assist for calls? We want to tap into the camera and then stream it using Azure while not touching the current setup.

**Comment by beelia** [comment]
@jnanadarshan, so sorry for the delay. HoloLens does allow for use of the camera while streaming in Remote Assist -- see [mixed reality capture](https://docs.microsoft.com/en-us/hololens/holographic-photos-and-videos#share-your-mixed-reality-photos-and-videos). Were you able to achieve your goal?

**Comment by beelia** [comment]
Closing the issue, no further questions or comments.
