### ISSUE TITLE
Update the Hololens Recovery page to include resetting user accounts.

### ISSUE THREAD

**Issue by JethroMV** [MicrosoftDocs/Hololens#57]
Hi all,
  The "Restart, reset, or recover HoloLens 2" docs works great when resetting a stuck device, but doesn't have any mention of the special process needed to reset a device when the users password/pin is lost.

  It seems like to reset a Hololens 2 without knowing the username/password you cannot use "Soft reset", "Hard Reset", or the "Advanced Recovery Companion" following the "Normal procedure".
  Instead you need to follow the  "Advanced Recovery Companion" steps but connect the device manually (the "Manual procedure" heading), even if it automatically discovers OK. If you don't use the Manual Procedure the Advanced Recovery Companion errors with `Your device appears to be locked. Please sign in to your device in order to continue`.

  Is it possible to add a note to this page telling users that to reset a user account they need to follow the Advanced Recovery Companion in the "Manual procedure" mode. Currently it reads like the manual procedure is only needed if you cannot automatically connect for some reason, as opposed to having different functionality.

eg perhaps change:
> If the HoloLens 2 doesn't start correctly or if Advanced Recovery Companion cannot detect the device, you may need to put the device into recovery mode: 

to. 
> If the HoloLens 2 doesn't start correctly, Advanced Recovery Companion cannot detect the device, or you do not have access to the logged in users password/PIN, you may need to put the device into recovery mode:

or add a note at the top of the page.

Thanks!
Jethro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd4de184-bdeb-2611-8d75-28376e30b0fc
* Version Independent ID: 7b330f9a-d1c0-72f9-0d00-d7fac13e7e00
* Content: [Restart, reset, or recover HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-recovery)
* Content Source: [hololens/hololens-recovery.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-recovery.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by evmill** [comment]
Suggested change made.
