### ISSUE TITLE
Hololens Mesh Application issue

### ISSUE THREAD

**Issue by 200335208** [MicrosoftDocs/Hololens#60]
[Enter feedback here]

Hello,

This is Jim from Loreal travel retail company.
As I am handling the Digital Twin Store Project and tested on VR collaboration application "Mesh"
But there may be some issues to display the 3D model or other format documents.

May I know if they're limited size to load and display the 3D model?

I tried loading some smaller same format 3D models was successful to display but the 25MB size was unsuccessful to display with an unknown errror.

And I tried JPG is working to display too. How about some documents format such as PDF or videos?

 Could you let me know all the requirements and limited information on the Mesh application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e67982e-6e73-e5cd-04eb-3c80568a99be
* Version Independent ID: 75498529-c75a-cdb8-43aa-7a87aa523aa3
* Content: [Give us feedback](https://docs.microsoft.com/en-us/hololens/hololens-feedback)
* Content Source: [hololens/hololens-feedback.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-feedback.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @evmill
* Microsoft Alias: **v-evmill**

**Comment by Nazeehe** [comment]
Hi,

Thanks for posting your question. 

There are limits on the models, yeah. The models need to be less than 75MB in size and less than 300k vertices. 

We only support loading jpg and png at the moment. Pdf and videos are planned features for future releases. 

Thanks!

**Comment by beelia** [comment]
#pleaseclose - resolved by a Commercial team engineer
