### ISSUE TITLE
Remove holograms needs steps

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/Hololens#62]
[Enter feedback here]

On https://docs.microsoft.com/en-us/hololens/hololens-environment-considerations#environment-management there need to be more detailed steps how to reach the settings, e.g. 
Settings > System > Holograms > Remove nearby holograms. Or, if needed, select Remove all holograms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95b5415-c6bd-d238-e667-17dd314cf7a3
* Version Independent ID: 54a2c58a-a9ba-c8ad-0b2c-54c2bc350814
* Content: [HoloLens environment considerations](https://docs.microsoft.com/en-us/hololens/hololens-environment-considerations)
* Content Source: [hololens/hololens-environment-considerations.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-environment-considerations.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by dstrome** [comment]
Please per request from @beelia
