### ISSUE TITLE
Wrong instructioni

### ISSUE THREAD

**Issue by vtieto** [MicrosoftDocs/Hololens#63]
The instruction for the redirect says " Be sure the path starts with mixed-reality-docs and ends with .md.," But in the example this is supposedly explaining, the path doesn't  start with or contain "mixed-reality-docs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c59d61be-3214-2d42-acbd-39a7ab959c90
* Version Independent ID: 619d205a-1e53-9273-2b56-d1fd73333e9c
* Content: [Contributing instructions](https://docs.microsoft.com/en-us/hololens/contributing)
* Content Source: [hololens/contributing.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/contributing.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @hferrone
* Microsoft Alias: **mattwoj**

**Comment by beelia** [comment]
@vieto, thanks for finding and helping me resolve this issue. The [corrected page](https://docs.microsoft.com/en-us/hololens/contributing)  has been published, and you can now remove this resolved issue.  Thanks again!
