### ISSUE TITLE
Disabling eye calibration on HoloLens 2

### ISSUE THREAD

**Issue by raphaelpaquin** [MicrosoftDocs/Hololens#64]
using latest release on holoLens 2 does not allow to disable eye calibration as it was possible in the past (switch button on/off)
This bring many issue when sharing the holoLens to multiple person for XR demonstration/test, explaining to each person what to do. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa319ad-e258-52c8-fa7b-aafcfbbdf385
* Version Independent ID: 1484d0bc-8612-f49d-4faa-f574dec49929
* Content: [Improve visual quality and comfort](https://docs.microsoft.com/en-us/hololens/hololens-calibration)
* Content Source: [hololens/hololens-calibration.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-calibration.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **xerxesb**

**Comment by beelia** [comment]
@raphaelpaquin, There's a good reason for requiring each XR10 user to step through the eye calibration process. The Trimble Connect for Holograms app needs additional eye gaze data for each user to achieve the precision and accuracy their HoloLens product requires.  So you can't disable eye calibration without contacting Trimble.
 
For more information, see their [white paper (https://fieldtech.trimble.com/resources/mixed-reality/white-paper-precision-and-accuracy-of-holograms-in-trimble-connect-for-hololens).

**Comment by beelia** [comment]
Closing the issue, no further questions or comments.
