### ISSUE TITLE
Can`t see new Chromium on Hololens

### ISSUE THREAD

**Issue by GabrielFranklin** [MicrosoftDocs/Hololens#67]
Hi, I recently updated my Hololens 2 to last windows version, however microsoft edge icon didn`t change for chromium. Also I can`t access pages that are only enabled by chromium.

How can I fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de7cd7f-ed53-733e-d702-92e413659cc4
* Version Independent ID: e73bec63-7d31-a707-f3bd-c4580bb81e04
* Content: [Introducing the new Microsoft Edge](https://docs.microsoft.com/en-us/hololens/hololens-new-edge)
* Content Source: [hololens/hololens-new-edge.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-new-edge.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @joyjaz
* Microsoft Alias: **v-jjaswinski**

**Comment by evmill** [comment]
Hello Gabriel,
What OS version is your HoloLens on? Settings -> System -> About should display this. You'll need to be running version 20346.1002 / 21H1 or newer. If you're on the correct build then please file a bug using [Feedback Hub](https://docs.microsoft.com/en-us/hololens/hololens-feedback) so engineers can look at this issue. 
If you are experiencing this issue on one device only, and you want a quick fix, you could likely [reset/reflash](https://docs.microsoft.com/en-us/hololens/hololens-recovery) the device. If you're being impacted on multiple devices then you might want to try reaching out to support.

**Comment by GabrielFranklin** [comment]
Thanks Evan,

I observed that the Edge icon wouldn`t change on start menu, even with no updates to download. So as this was the only device like this, I re-flahsed with Advanced Companion with last OS, and it is now working.

Can`t tell what version it stopped at, but we can say there is an error that prevents the edge from being updated (old version was open and being used at the update download time...that could be it?)

Best Regards,
Gabriel.

De: Evan Miller ***@***.***>
Enviada em: Monday, November 15, 2021 8:58 PM
Para: MicrosoftDocs/Hololens ***@***.***>
Cc: Gabriel Franklin ***@***.***>; Author ***@***.***>
Assunto: [EXTERNAL] Re: [MicrosoftDocs/Hololens] Can`t see new Chromium on Hololens (Issue #67)

External Sender: Use caution with links/attachments.


Hello Gabriel,
What OS version is your HoloLens on? Settings -> System -> About should display this. You'll need to be running version 20346.1002 / 21H1 or newer. If you're on the correct build then please file a bug using Feedback Hub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fhololens%2Fhololens-feedback&data=04%7C01%7Cgabriel.franklin%40halliburton.com%7Cd04de1ac3ad247e46c4708d9a893b7e2%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C637726174671449464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2M%2Fn5vo6QhMJ2MByOV1vjri2X5Acjxi%2F1pOGzm284G4%3D&reserved=0> so engineers can look at this issue.
If you are experiencing this issue on one device only, and you want a quick fix, you could likely reset/reflash<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fhololens%2Fhololens-recovery&data=04%7C01%7Cgabriel.franklin%40halliburton.com%7Cd04de1ac3ad247e46c4708d9a893b7e2%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C637726174671449464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cP3k9m6iZX8LcuyG3uLnj1O3Qmv3WhWtg0yKFnF8GgU%3D&reserved=0> the device. If you're being impacted on multiple devices then you might want to try reaching out to support.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FHololens%2Fissues%2F67%23issuecomment-969459843&data=04%7C01%7Cgabriel.franklin%40halliburton.com%7Cd04de1ac3ad247e46c4708d9a893b7e2%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C637726174671459460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HxaDqaJBudqOGR9%2BhWRb7oZ1pEtlar9%2FJknOQ20TBAM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUC3MF255NVQNONKGYVVISDUMGM7PANCNFSM5HVOG3GQ&data=04%7C01%7Cgabriel.franklin%40halliburton.com%7Cd04de1ac3ad247e46c4708d9a893b7e2%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C637726174671469457%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6uTfb%2ByFgiD%2BAOTGuQYArC5JBVCFkBwwNPFi10fZiLE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cgabriel.franklin%40halliburton.com%7Cd04de1ac3ad247e46c4708d9a893b7e2%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C637726174671479452%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wMm0AIHcbAwvajKfZDKGd1ykbX%2Bs2aSmkrKiH6Tc6H0%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cgabriel.franklin%40halliburton.com%7Cd04de1ac3ad247e46c4708d9a893b7e2%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C637726174671479452%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ehHs3%2BDSEIzyc8jdtYdyrxsIEAl4krIa87ENtwiyr%2F4%3D&reserved=0>.

This e-mail, including any attached files, may contain confidential and privileged information for the sole use of the intended recipient. Any review, use, distribution, or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive information for the intended recipient), please contact the sender by reply e-mail and delete all copies of this message.

**Comment by evmill** [comment]
Closing since issue was resolved.
