### ISSUE TITLE
Device Portal file upload/download times out

### ISSUE THREAD

**Issue by atolegen** [MicrosoftDocs/Hololens#68]
My HL2 's OS version is : 20348.1438.arm64fre.fe_release_svc_sydney_rel_prod.211103-1741. I am still having this issue. I need to upload 40 000 images to localappdata. I tried uploading these files to knownfolders but HL got frozen after 2000 images. I am trying using deviceportalwrapper. I was able to connect to hololens, capture frames, and download the image but I was not able to upload files. It waits for a long time and crashes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ce6508-c321-3e04-5066-514e01dacaa7
* Version Independent ID: 45765e7f-8b9b-fa59-91dc-50ac24b2648c
* Content: [HoloLens Device Troubleshooting](https://docs.microsoft.com/en-us/hololens/hololens-troubleshooting#fixed---downloading-locked-files-doesnt-error)
* Content Source: [hololens/hololens-troubleshooting.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-troubleshooting.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @evmill
* Microsoft Alias: **v-evmill**

**Comment by evmill** [comment]
Hello @atolegen could you tell me a bit more about your use case? Is this a production or developer scenario? I'm wondering if based on how the files are used/loaded perhaps there's another way to send these files to the device.

**Comment by atolegen** [comment]
Hi @evmill. I am a Ph.D. student at Nazarbayev University. I have collected a dataset of images as a preliminary design for the experiment with human subjects. I would like to upload it to HL 2 and visualize them during the experiment. I want to upload the images to localappdata. So far, I tried uploading images to Hololens using Rest API (in UWP and javascript) only. I can't upload even a single image. Are there any other ways to upload files to HL2? And one more question. Why does HL2 get frozen after uploading 2000 images to known folders?
My functions for connecting and uploading a file in the UWP C# project:

using Microsoft.Tools.WindowsDevicePortal;
//////////////////////////////
        private DevicePortal portal;
        private Certificate certificate;
        static string HoloLensUrl =  "http://127.0.0.1:10080/";
//////////////////////////////
        private async void uploadFile_Click(object sender, RoutedEventArgs e)
        {
           Task uploadTask = new Task(
            async () =>
            {
                string filePath = "100.jpg";
                Console.WriteLine("filePath = " + filePath);

                await portal.UploadFileAsync("LocalAppData", "100.jpg", "LocalState", "Template3D_1.0.0.0_arm64__pzq3xp76mxafg");
                Console.WriteLine("uploading finished!");
            });
            uploadTask.Start();
        }
///////////////////////////////////////////////
       //function for connecting to Hololens 2 from PC
        private async void connect_Click(object sender, RoutedEventArgs e)
        {
            
            portal = new DevicePortal(
                new DefaultDevicePortalConnection(HoloLensUrl, "login","password"));

            StringBuilder sb = new StringBuilder();

            sb.Append(this.messageb.Text);
            sb.AppendLine("Connecting...");
            this.messageb.Text = sb.ToString();
            portal.ConnectionStatus += (portal, connectArgs) =>
            {
                if (connectArgs.Status == DeviceConnectionStatus.Connected)
                {
                    sb.Append("Connected to: ");
                    sb.AppendLine(portal.Address);
                    sb.Append("OS version: ");
                    sb.AppendLine(portal.OperatingSystemVersion);
                    sb.Append("Device family: ");
                    sb.AppendLine(portal.DeviceFamily);
                    sb.Append("Platform: ");
                    sb.AppendLine(String.Format("{0} ({1})",
                        portal.PlatformName,
                        portal.Platform.ToString()));
                }
                else if (connectArgs.Status == DeviceConnectionStatus.Failed)
                {
                    sb.AppendLine("Failed to connect to the device.");
                    sb.AppendLine(connectArgs.Message);
                }
            };
            try
            {
                // If the user wants to allow untrusted connections, make a call to GetRootDeviceCertificate
                // with acceptUntrustedCerts set to true. This will enable untrusted connections for the
                // remainder of this session.

                this.certificate = await portal.GetRootDeviceCertificateAsync(true);
                
                await portal.ConnectAsync(manualCertificate: this.certificate);
                sb.AppendLine("connected");
            }
            catch (Exception exception)
            {
                sb.AppendLine(exception.Message);
            }
            this.messageb.Text = sb.ToString();
        }

I was able to connect to HL2 from PC, get wifi information, capture a frame, get a file but was not able to upload a single file to HL2. I am using VS 2017 since WindowsDevicePortalWrapper (https://github.com/microsoft/WindowsDevicePortalWrapper) works in that version of VS only. I have tried HttpHandler module and Windows.Web.Http API in C# and javascript scripts but all of them are in vain. And I looked for solutions in forums. There is no solution in those forums. I found out that this issue exists for a long time in UWP devices.

**Comment by atolegen** [comment]
Hello @evmill. Did you understand my issue? Do you have some suggestions?

**Comment by evmill** [comment]
@pbarnettms Do you have any insights to this Device Portal issue?

**Comment by pbarnettms** [comment]
This is not a known issue.  The best course of action would be to use Feedback Hub to file a bug and allow it to collect diagnostics.  Given the reference to "this issue exists for a long time in UWP devices", please provide links to where this is mentioned.

**Comment by evmill** [comment]
Closing stale issue.
