### ISSUE TITLE
Confusing wording regarding support for external microphones & OS versions

### ISSUE THREAD

**Issue by msft-bstru** [MicrosoftDocs/Hololens#74]
There's a line on this page that reads as follows:
- External microphones cannot be used in builds prior to [Windows Holographic, version 21H1](https://docs.microsoft.com/en-us/hololens/hololens-release-notes#windows-holographic-version-21h1) **and higher.**

**Emphasis** mine.

Should this read "and below"? From what I understand this to mean, external microphones cannot be used in any builds since it calls out those _prior_ to 21H1 **and** _higher_ than 21H1.

A customer brought this to my attention, it's unclear to them as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff4a915-cffe-849d-800b-7f339ddb01c0
* Version Independent ID: 6f1c3aa3-8a90-ed5e-9d93-3f09680acaa8
* Content: [Connect to Bluetooth and USB-C devices](https://docs.microsoft.com/en-us/hololens/hololens-connect-devices#usb-c-external-microphone-support)
* Content Source: [hololens/hololens-connect-devices.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-connect-devices.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by evmill** [comment]
PR has been made and merged, changes will go live this afternoon.
