### ISSUE TITLE
"set up Azure AD join in your organization" is duplicate text

### ISSUE THREAD

**Issue by raidenGitHub** [MicrosoftDocs/Hololens#76]
[The phrase,  "set up Azure AD join in your organization." is mentioned twice in the article. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3248f36b-deaf-9562-a030-f3d28ae7e215
* Version Independent ID: 39b1ac9b-fa52-b52d-e970-de1c19ed1c81
* Content: [Configure HoloLens by using a provisioning package (HoloLens)](https://docs.microsoft.com/en-us/hololens/hololens-provisioning)
* Content Source: [hololens/hololens-provisioning.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-provisioning.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **v-beehanson**

**Comment by evmill** [comment]
Thanks for pointing this out. I've made a PR to fix this.
