### ISSUE TITLE
Link to drivers

### ISSUE THREAD

**Issue by TheAxeManGa** [MicrosoftDocs/Hololens#79]
[Enter feedback here]

Hello. I think it would be very useful to have a link to the latest drivers for the Holos. I have 3 bricked units showing 
QUSB_BULK_CID in the Device Manager under 'Other devices'. With the proper signed drivers this would be very easy to fix!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd4de184-bdeb-2611-8d75-28376e30b0fc
* Version Independent ID: 7b330f9a-d1c0-72f9-0d00-d7fac13e7e00
* Content: [Restart, reset, or recover HoloLens 2](https://docs.microsoft.com/en-us/hololens/hololens-recovery?msclkid=301a96b2c16d11ec81cb408fd2909774)
* Content Source: [hololens/hololens-recovery.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-recovery.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **qianwen**

**Comment by evmill** [comment]
1.	Right click QUSB_BULK and try to update automatically.  This will probably fail, but can help move the process along.
2.	Open up Settings and go to Update & Security.
3.	Open Optional Updates and check for a Qualcomm driver.
4.	Install the update (if available; it may take a hot minute for the driver to appear).
5.	Check Device Manager and see if the device now enumerates under Ports as a Qualcomm HS-USB device.
6.	Use ARC to recover device.
7.	Hope and don't touch the device until it comes back to life.

You can also check out: [Improving the update discoverability experience - Microsoft Tech Community](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/improving-the-update-discoverability-experience/ba-p/1585674)
